name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          pip install -e .
          pip install .[dev]
      - name: Lint
        run: make lint
      - name: Unit tests
        run: make unit
      - name: Integration tests
        run: make integration
