name: Terraform
on:
  push: { paths: ["infra/terraform/**"] }
  pull_request: { paths: ["infra/terraform/**"] }
jobs:
  tf:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: infra/terraform } }
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan -no-color -var="project=featback"
